### PR TITLE
Fix type mismatch for conrod_piston::draw::Context fields 

### PR DESCRIPTION
**Pull request by lubosmudrak**
This pull request fixes a type mismatch for fields "view" and "transform" in conrod_piston::draw::Context fields.

### CODE REVIEW

**Comment by bvssvni** [comment]
This is incorrect. What is the background for this change?

**Comment by lubosmudrak** [comment]
I am using conrod_piston as a backend for drawing a window. With current latesf official versions of conrod_core(0.73.0) and piston_window(0.120.0) I get the following error:

```
error[E0308]: mismatched types
   --> src\gui.rs:103:17
    |
103 |                 context,
    |                 ^^^^^^^ expected struct `conrod_piston::draw::Context`, found struct `piston_window::Context`

    |
    = note: perhaps two different versions of crate `graphics` are being used?

```

conrod_piston backend in Conrod and piston_window crate do indeed use a diferrent versions of piston2d-graphics, versions 0.37.0 and 0.40.0. After updating dependecy to piston2d-graphics in both crates to the same version the compiler started to complain that fields "view" and "transform" have incorrect types so I changed them and then my code compiled.

Should I provide a minimal example to be tested?

Also could you please elaborate why is changing the type of those two fields from Matrix2d to [[f64; 3]; 2] incorrect? 

Thank you for your feedback.

**Comment by bvssvni** [comment]
It is incorrect because the `Scalar` is used to define e.g. `Matrix2d`.

Could there be 3 different versions?

**Comment by lubosmudrak** [comment]
Thank you for clarifying information. I will check if there are any version mismatches and then I will implement a correct fix for this problem.

P.S. Sorry for late response, I am putting a lot of time in other projects.

**Comment by lubosmudrak** [comment]
Issue disappeared after fetching latest version of repository with conrod and using that as a dependency for my app. Whatever caused it in the past is fixed and this pull request is therefore unnecessary now. Sorry for inconvenience I caused, I will now close this pull request.

**Comment by bvssvni** [comment]
@lubosmudrak no problem!

**Pull request closed without merging**
