### PR TITLE
Add more matrix extraction functions

### PR DESCRIPTION
**Pull request by vpzomtrrfrt**
In line with `get_scale`, I added `get_translation` and `get_rotation_radians`.

I'm not super familiar with transformation matrices, but these seem to work, at least for the test cases

### CODE REVIEW

**Comment by bvssvni** [comment]
Can you add `get_shear` too? This will make it complete.

**Comment by vpzomtrrfrt** [comment]
Added

**Comment by bvssvni** [comment]
I need to investigate a bit about the specific semantics, but I like the idea.

For 2D objects there is a natural way of applying transformations, e.g. `translate, rotate, scale, shear`. It could happen that all these must be analyzed at the same time. I got some old code in C# that I can look at, which does precisely this, so I will try to translate it into Rust and see what happens.

The other use case is when you are drawing borders of absolute width (e.g. cartoons) and you need to know an estimate for scale. This will only work for uniform scaling.

There could be that `get_scale` is the second case and not compatible with the first one. I think this is likely.

However, you are providing valuable feedback with this PR, because we need to understand better the use cases.

**Comment by bvssvni** [comment]
Hmm... if I understand this correctly, `get_scale` works for non-uniform scaling, which is probably an improved version I added instead of the uniform scaling estimate I used in the previous C# project. Although absolute border width requires uniform scaling, the loss of information is after calling `get_scale`.

I think that's why the semantics seems confusing to me, since `get_scale` might, or might not, be compatible with the natural way of applying transformations.

I need to investigate this more.

**Comment by bvssvni** [comment]
The old code I looked at uses the inverse matrix together with special points and vectors. So far, I have figured out:

- Origo gives the translation
- Angle of x-axis gives the rotation

This means `get_translation` and `get_rotation_radians` are probably wrong (*don't to fix this yet!*).

I might have derived the `get_scale` using the inverse matrix, but this is not certain yet.

**Comment by bvssvni** [comment]
I need to investigate this more. For now, I think we should wait adding more features to this library. Matrix extraction is not a commonly used feature, so it might fit into a new library. What do you think?

**Comment by bvssvni** [comment]
Closing for now.

**Pull request closed without merging**
